# Generated by Django 2.1.7 on 2019-03-25 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bankName', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10)),
                ('cv', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AvailablePaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(max_length=20)),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commisionName', models.CharField(max_length=20)),
                ('description', models.CharField(default='no description', max_length=20)),
                ('commisionPercentageRate', models.FloatField(default=0.0)),
                ('taxable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('elementaryEducation', models.CharField(max_length=50)),
                ('secondaryEducation', models.CharField(max_length=50)),
                ('HigherEducation', models.CharField(max_length=50)),
                ('professionalQualification', models.CharField(max_length=50)),
                ('postGradEducation', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentDeduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deductionName', models.CharField(max_length=20)),
                ('deductionAmount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateName', models.CharField(max_length=10)),
                ('rateBasicAmount', models.FloatField(default=0.0)),
                ('ratePercentage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='InternalDeduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='no description', max_length=20)),
                ('deductionAmount', models.FloatField(default=0.0)),
                ('settled', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internaldeductions', to='hrisapp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='InternalDeductionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deductionName', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('taxable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeavesAndHoliDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paymentDate', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default='False')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentStatuses', to='hrisapp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAddition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
                ('additionAmount', models.FloatField(default=0.0)),
                ('settled', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SalaryAdditions', to='hrisapp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAdditionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('additionTypeName', models.CharField(max_length=20)),
                ('description', models.CharField(default='', max_length=20)),
                ('taxable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('basicPay', models.FloatField(default=0.0)),
                ('commision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salarytypes', to='hrisapp.Commision')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesWorth', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrisapp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='UserAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timeIn', models.TimeField(blank=True, null=True)),
                ('timeOut', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrisapp.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLeavesAndHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('description', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('leaveType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrisapp.LeavesAndHoliDays')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacantPost', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='salaryaddition',
            name='salaryAdditionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaryadditions', to='hrisapp.SalaryAdditionType'),
        ),
        migrations.AddField(
            model_name='internaldeduction',
            name='internalDeductionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internaldeductions', to='hrisapp.InternalDeductionType'),
        ),
        migrations.AddField(
            model_name='applicants',
            name='vacancyAppliedTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrisapp.Vacancy'),
        ),
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='hrisapp.Department'),
        ),
        migrations.AddField(
            model_name='account',
            name='internalDeductions',
            field=models.ManyToManyField(through='hrisapp.InternalDeduction', to='hrisapp.InternalDeductionType'),
        ),
        migrations.AddField(
            model_name='account',
            name='prefferedPaymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='hrisapp.AvailablePaymentMethod'),
        ),
        migrations.AddField(
            model_name='account',
            name='salaryAdditions',
            field=models.ManyToManyField(through='hrisapp.SalaryAddition', to='hrisapp.SalaryAdditionType'),
        ),
        migrations.AddField(
            model_name='account',
            name='salaryType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='hrisapp.SalaryType'),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
