# Generated by Django 2.1.7 on 2019-03-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='department',
        ),
    ]
