# Generated by Django 2.0.5 on 2019-03-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0002_remove_paymentstatus_totalpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='commision',
        ),
        migrations.AddField(
            model_name='salarytype',
            name='basicPay',
            field=models.FloatField(default=0.0),
        ),
    ]
