# Generated by Django 2.0.5 on 2019-03-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0003_auto_20190306_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='totalPay',
            field=models.FloatField(default=0.0),
        ),
    ]
