# Generated by Django 2.1.7 on 2019-03-29 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0003_auto_20190328_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldeduction',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internaldeduction',
            name='repaymentPeriod',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salaryaddition',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
