# Generated by Django 2.1.7 on 2019-03-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0004_auto_20190329_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaldeduction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryaddition',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
