# Generated by Django 2.0.5 on 2019-03-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0004_paymentstatus_totalpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='totalPay',
        ),
    ]
