# Generated by Django 2.1.7 on 2019-03-29 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0005_auto_20190329_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaldeduction',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 29, 9, 49, 56, 713754)),
        ),
        migrations.AlterField(
            model_name='salaryaddition',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 29, 9, 49, 56, 714440)),
        ),
    ]
