# Generated by Django 2.0.5 on 2019-03-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0005_remove_paymentstatus_totalpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bankName',
        ),
    ]
