# Generated by Django 2.0.5 on 2019-03-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0006_remove_account_bankname'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='totalPay',
            field=models.FloatField(default=0.0),
        ),
    ]
