# Generated by Django 2.0.5 on 2019-03-06 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0007_paymentstatus_totalpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bankName',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
