# Generated by Django 2.1.7 on 2019-04-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0007_auto_20190401_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bankAccountName',
            field=models.CharField(blank=True, default='none given', max_length=20),
        ),
    ]
