# Generated by Django 2.0.5 on 2019-03-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0008_account_bankname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatus',
            name='totalPay',
        ),
    ]
