# Generated by Django 2.0.5 on 2019-03-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0010_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='basicPay',
            field=models.FloatField(default=0.0),
        ),
    ]
