# Generated by Django 2.0.5 on 2019-03-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0011_account_basicpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaldeduction',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salaryaddition',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
