# Generated by Django 2.0.5 on 2019-03-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrisapp', '0012_auto_20190307_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='basicPay',
        ),
    ]
